import { PropsWithChildren } from 'react';
import { Pressable, StyleSheet, Text, View, ViewStyle } from 'react-native';
import { colors, radius, shadow } from '@/constants/theme';
export function Card({children,style}:{children:React.ReactNode;style?:ViewStyle}){return <View style={[s.card,style]}>{children}</View>}
export function SectionTitle({title,action}:{title:string;action?:React.ReactNode}){return <View style={s.row}><Text style={s.title}>{title}</Text>{action}</View>}
export function Chip({label,active,onPress,tint}:{label:string;active?:boolean;onPress?:()=>void;tint?:string}){return <Pressable onPress={onPress} style={[s.chip,active&&{backgroundColor:tint||colors.ink,borderColor:tint||colors.ink}]}><Text style={[s.chipText,active&&{color:tint?colors.ink:colors.white}]}>{label}</Text></Pressable>}
export function Button({children,onPress,kind='primary',style}:{children:React.ReactNode;onPress?:()=>void;kind?:'primary'|'soft'|'ghost';style?:ViewStyle}){return <Pressable onPress={onPress} style={({pressed})=>[s.button,kind==='soft'&&s.soft,kind==='ghost'&&s.ghost,style,pressed&&{opacity:.72}]}><Text style={[s.buttonText,kind!=='primary'&&{color:colors.ink}]}>{children}</Text></Pressable>}
export function Progress({value,color=colors.green}:{value:number;color?:string}){return <View style={s.track}><View style={[s.fill,{width:`${value}%`,backgroundColor:color}]}/></View>}
export function ScreenHeader({eyebrow,title,right}:{eyebrow?:string;title:string;right?:React.ReactNode}){return <View style={s.header}><View>{eyebrow&&<Text style={s.eyebrow}>{eyebrow}</Text>}<Text style={s.headerTitle}>{title}</Text></View>{right}</View>}
export function Label({children}:PropsWithChildren){return <Text style={s.label}>{children}</Text>}
const s=StyleSheet.create({card:{backgroundColor:colors.paper,borderRadius:radius.lg,borderWidth:1,borderColor:colors.line,padding:18,...shadow},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:12},title:{fontSize:20,fontWeight:'700',color:colors.ink,letterSpacing:-.4},chip:{borderWidth:1,borderColor:colors.line,borderRadius:radius.pill,paddingHorizontal:13,paddingVertical:8,backgroundColor:colors.paper},chipText:{fontSize:12,fontWeight:'600',color:colors.muted},button:{minHeight:46,borderRadius:radius.md,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center',paddingHorizontal:17},soft:{backgroundColor:colors.lavender},ghost:{backgroundColor:'transparent',borderWidth:1,borderColor:colors.line},buttonText:{color:colors.white,fontWeight:'700',fontSize:14},track:{height:7,borderRadius:8,backgroundColor:colors.line,overflow:'hidden'},fill:{height:7,borderRadius:8},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:22},eyebrow:{textTransform:'uppercase',fontSize:11,fontWeight:'700',letterSpacing:1.3,color:colors.muted,marginBottom:5},headerTitle:{fontSize:31,fontWeight:'700',letterSpacing:-1,color:colors.ink},label:{fontSize:11,textTransform:'uppercase',letterSpacing:1,fontWeight:'700',color:colors.muted}});
