import { useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors, radius } from '@/constants/theme';
import { Button, Label } from '@/components/common/UI';
import { usePlannerStore } from '@/store/usePlannerStore';
import { Task } from '@/types';
const parsed=[['Combine Data','Flexible · 6h · Sunday'],['Write RP Outline','Flexible · 2–3h · Friday · High effort'],['Contact 5 Supervisors','Flexible · Wednesday'],['Cantonese','Routine · 30m/day'],['Meeting','Fixed · Tomorrow 15:00']];
export function AIInputSheet({visible,onClose}:{visible:boolean;onClose:()=>void}){const [text,setText]=useState('');const [show,setShow]=useState(false);const add=usePlannerStore(s=>s.addParsedTasks);const confirm=()=>{const now=Date.now();add(parsed.map((p,i)=>({id:`ai-${now}-${i}`,title:p[0],type:p[1].startsWith('Fixed')?'fixed':p[1].startsWith('Routine')?'routine':'flexible',duration:i===0?360:30,deadline:p[1].includes('Friday')?'Friday':undefined,priority:'medium',effort:i===1?'high':'medium',scheduledStart:'Unscheduled',scheduledEnd:'',status:'todo',locked:p[1].startsWith('Fixed'),coins:25} as Task)));onClose();setShow(false);setText('')};return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={s.backdrop} onPress={onClose}/><View style={s.sheet}><View style={s.handle}/><View style={s.head}><View><Label>Gentle planning assistant</Label><Text style={s.title}>What changed?</Text></View><Pressable onPress={onClose}><Ionicons name="close" size={24} color={colors.ink}/></Pressable></View><Text style={s.help}>Add tasks, plans, or a messy brain-dump. We’ll turn it into something workable.</Text><TextInput multiline value={text} onChangeText={setText} placeholder="This week I need to combine data for 6 hours…" placeholderTextColor="#A4A29D" style={s.input}/>{!show?<Button onPress={()=>setShow(true)}>✨ Make sense of this</Button>:<ScrollView style={{maxHeight:270}}><Text style={s.found}>I found 5 things</Text>{parsed.map(([title,meta])=><View style={s.result} key={title}><View style={s.dot}/><View><Text style={s.resultTitle}>{title}</Text><Text style={s.meta}>{meta}</Text></View><Ionicons name="create-outline" size={18} color={colors.muted}/></View>)}<View style={s.actions}><Button style={{flex:1}} onPress={confirm}>Confirm all</Button><Button style={{flex:1}} kind="ghost" onPress={()=>setShow(false)}>Edit input</Button></View></ScrollView>}</View></Modal>}
const s=StyleSheet.create({backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(50,48,44,.26)'},sheet:{position:'absolute',bottom:0,left:0,right:0,maxHeight:'88%',backgroundColor:colors.cream,borderTopLeftRadius:28,borderTopRightRadius:28,padding:22,paddingBottom:38},handle:{width:42,height:4,borderRadius:4,backgroundColor:colors.line,alignSelf:'center',marginBottom:20},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:25,fontWeight:'700',color:colors.ink,marginTop:4},help:{fontSize:14,lineHeight:20,color:colors.muted,marginVertical:12},input:{minHeight:120,textAlignVertical:'top',backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:radius.md,padding:15,fontSize:15,color:colors.ink,marginBottom:14},found:{fontSize:13,fontWeight:'700',color:colors.green,marginVertical:12},result:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:12,borderBottomWidth:1,borderBottomColor:colors.line},dot:{width:8,height:8,borderRadius:8,backgroundColor:colors.purple},resultTitle:{fontWeight:'700',fontSize:14,color:colors.ink},meta:{fontSize:12,color:colors.muted,marginTop:3},actions:{flexDirection:'row',gap:10,marginTop:16}});

