import { useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Card, Chip, ScreenHeader } from '@/components/common/UI';
import { colors } from '@/constants/theme';
import { usePlannerStore } from '@/store/usePlannerStore';
import { TaskType } from '@/types';
const typeColor:Record<TaskType,string>={fixed:colors.peach,flexible:colors.lavender,routine:colors.sage};
export default function Calendar(){const [view,setView]=useState('Week');const tasks=usePlannerStore(s=>s.tasks);return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.page}><ScreenHeader eyebrow="August 10 – 16" title="Calendar" right={<Text style={s.today}>Today</Text>}/><View style={s.switch}>{['Day','Week','Month'].map(v=><Chip key={v} label={v} active={view===v} tint={colors.blue} onPress={()=>setView(v)}/>)}</View><View style={s.legend}>{(['fixed','flexible','routine'] as TaskType[]).map(t=><Text key={t} style={s.legendText}><Text style={{color:typeColor[t]}}>● </Text>{t}</Text>)}<Text style={s.legendText}><Text style={{color:colors.yellow}}>● </Text>deadline</Text></View><Card style={s.calendar}><View style={s.days}><View style={{width:38}}/>{['M 10','T 11','W 12','T 13','F 14','S 15','S 16'].map((d,i)=><View style={[s.day,i===6&&s.selected]} key={d}><Text style={[s.dayText,i===6&&{color:colors.ink}]}>{d}</Text></View>)}</View><View style={s.grid}>{[12,13,14,15,16,17,18,19,20].map((h,row)=><View style={s.hour} key={h}><Text style={s.hourText}>{h}:00</Text><View style={s.hourLine}/>{row===2&&<View style={s.nowLine}><View style={s.nowDot}/></View>}</View>)}{tasks.slice(0,5).map((task,i)=><View key={task.id} style={[s.event,{top:70+i*49,left:45+(i%3)*70,backgroundColor:typeColor[task.type]}]}><Text numberOfLines={2} style={s.eventTitle}>{task.locked?'🔒 ':''}{task.title}</Text><Text style={s.eventTime}>{task.scheduledStart}</Text></View>)}</View></Card><Text style={s.tip}>Flexible blocks can move when reality changes. Fixed plans stay safely locked.</Text></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},page:{padding:20,paddingBottom:120},today:{fontSize:12,fontWeight:'700',color:colors.green,borderWidth:1,borderColor:colors.sage,borderRadius:20,paddingHorizontal:12,paddingVertical:7},switch:{flexDirection:'row',gap:7,marginBottom:15},legend:{flexDirection:'row',gap:10,flexWrap:'wrap',marginBottom:12},legendText:{fontSize:10,color:colors.muted,textTransform:'capitalize'},calendar:{padding:10,overflow:'hidden'},days:{flexDirection:'row',height:34,alignItems:'center',borderBottomWidth:1,borderColor:colors.line},day:{flex:1,alignItems:'center',paddingVertical:6,borderRadius:10},selected:{backgroundColor:colors.yellow},dayText:{fontSize:9,color:colors.muted,fontWeight:'700'},grid:{height:470,position:'relative'},hour:{height:52,flexDirection:'row',alignItems:'flex-start'},hourText:{width:38,fontSize:9,color:colors.muted,marginTop:-5},hourLine:{flex:1,borderTopWidth:1,borderColor:colors.line},nowLine:{position:'absolute',left:38,right:0,top:18,height:1,backgroundColor:colors.coral,zIndex:4},nowDot:{width:6,height:6,borderRadius:4,backgroundColor:colors.coral,marginTop:-2},event:{position:'absolute',width:66,minHeight:42,borderRadius:8,padding:6,borderLeftWidth:2,borderLeftColor:'rgba(70,70,70,.25)'},eventTitle:{fontSize:9,fontWeight:'700',color:colors.ink},eventTime:{fontSize:8,color:colors.muted,marginTop:2},tip:{fontSize:12,textAlign:'center',color:colors.muted,lineHeight:18,marginTop:14,paddingHorizontal:20}});

