import { useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Card, Chip, Label, Progress, ScreenHeader, SectionTitle } from '@/components/common/UI';
import { colors } from '@/constants/theme';
import { usePlannerStore } from '@/store/usePlannerStore';
import { Goal } from '@/types';
const statusTint={focus:colors.lavender,maintenance:colors.sage,shelved:colors.blue};
export default function Goals(){const goals=usePlannerStore(s=>s.goals);const [filter,setFilter]=useState('All');const [selected,setSelected]=useState<Goal|null>(null);return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.page}><ScreenHeader eyebrow="Direction, not pressure" title="Goals" right={<View style={s.badge}><Ionicons name="leaf-outline" size={16} color={colors.green}/><Text style={s.badgeText}>Steady</Text></View>}/><Text style={s.intro}>Keep what matters visible. Shelving a goal is a thoughtful choice, never a failure.</Text><View style={s.filters}>{['All','Focus','Maintenance','Shelved'].map(v=><Chip key={v} label={v} active={filter===v} tint={colors.yellow} onPress={()=>setFilter(v)}/>)}</View>{goals.filter(g=>filter==='All'||g.status===filter.toLowerCase()).map(goal=><Pressable key={goal.id} onPress={()=>setSelected(goal)}><Card style={s.goal}><View style={s.goalTop}><View style={{flex:1}}><Text style={s.goalTitle}>{goal.title}</Text><Text style={s.focus}>{goal.currentFocus[0]}</Text></View><Text style={[s.status,{backgroundColor:statusTint[goal.status]}]}>{goal.status}</Text></View>{goal.status!=='shelved'?<><View style={s.progressLabel}><Text style={s.small}>Overall progress</Text><Text style={s.percent}>{goal.progress}%</Text></View><Progress value={goal.progress} color={goal.status==='focus'?colors.purple:colors.green}/></>:<Text style={s.rest}>Resting here until there’s more space.</Text>}<View style={s.open}><Text style={s.openText}>See the next layer</Text><Ionicons name="arrow-forward" size={16} color={colors.muted}/></View></Card></Pressable>)}</ScrollView><GoalSheet goal={selected} close={()=>setSelected(null)}/></SafeAreaView>}
function GoalSheet({goal,close}:{goal:Goal|null;close:()=>void}){const [tab,setTab]=useState('Overview');if(!goal)return null;return <Modal visible transparent animationType="slide"><Pressable style={s.backdrop} onPress={close}/><View style={s.sheet}><View style={s.sheetHead}><View><Label>{goal.status} goal</Label><Text style={s.sheetTitle}>{goal.title}</Text></View><Pressable onPress={close}><Ionicons name="close" size={24}/></Pressable></View><View style={s.filters}>{['Overview','Breakdown','Tasks'].map(v=><Chip key={v} label={v} active={tab===v} tint={colors.lavender} onPress={()=>setTab(v)}/>)}</View>{tab==='Overview'?<><SectionTitle title={`${goal.progress}% overall`}/><Progress value={goal.progress} color={colors.purple}/><Text style={s.subhead}>Current focus</Text>{goal.currentFocus.map(x=><Text key={x} style={s.bullet}>○  {x}</Text>)}<View style={s.insight}><Label>✨ AI insight</Label><Text style={s.insightText}>RP Outline is due in 3 days. Consider giving it one small block today.</Text></View></>:tab==='Breakdown'?<View style={s.layers}>{['Milestone · Research proposal ready','This month · Build a complete draft','This week · Shape the outline','Today · Create 3 rough headings'].map((x,i)=><View key={x} style={s.layer}><Text style={s.layerNumber}>0{i+1}</Text><Text style={s.layerText}>{x}</Text></View>)}</View>:<View>{goal.milestones.map(x=><View key={x} style={s.taskRow}><View style={s.check}/><Text style={s.layerText}>{x}</Text></View>)}</View>}</View></Modal>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},page:{padding:20,paddingBottom:120},badge:{flexDirection:'row',gap:5,backgroundColor:colors.sage,padding:9,borderRadius:20},badgeText:{fontSize:11,fontWeight:'700',color:colors.green},intro:{color:colors.muted,fontSize:14,lineHeight:21,marginTop:-8,marginBottom:16,maxWidth:330},filters:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:15},goal:{marginBottom:12},goalTop:{flexDirection:'row',alignItems:'flex-start'},goalTitle:{fontSize:19,fontWeight:'700',color:colors.ink},focus:{fontSize:12,color:colors.muted,marginTop:4},status:{fontSize:9,textTransform:'uppercase',fontWeight:'800',letterSpacing:.8,paddingHorizontal:9,paddingVertical:6,borderRadius:12,overflow:'hidden'},progressLabel:{flexDirection:'row',justifyContent:'space-between',marginTop:18,marginBottom:7},small:{fontSize:10,color:colors.muted},percent:{fontSize:11,fontWeight:'700',color:colors.ink},rest:{fontSize:12,color:colors.muted,marginTop:14,fontStyle:'italic'},open:{flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:6,marginTop:15},openText:{fontSize:11,fontWeight:'700',color:colors.muted},backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(50,48,44,.25)'},sheet:{position:'absolute',bottom:0,left:0,right:0,minHeight:'69%',backgroundColor:colors.cream,borderTopLeftRadius:28,borderTopRightRadius:28,padding:24,paddingBottom:42},sheetHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:16},sheetTitle:{fontSize:26,fontWeight:'700',color:colors.ink,marginTop:4},subhead:{fontSize:12,fontWeight:'700',color:colors.ink,marginTop:24,marginBottom:8,textTransform:'uppercase'},bullet:{fontSize:14,color:colors.ink,paddingVertical:6},insight:{backgroundColor:colors.yellow,borderRadius:16,padding:16,marginTop:18},insightText:{fontSize:13,lineHeight:20,color:colors.ink,marginTop:7},layers:{marginTop:8},layer:{flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderColor:colors.line,paddingVertical:16},layerNumber:{fontSize:10,fontWeight:'800',color:colors.purple,width:32},layerText:{fontSize:14,color:colors.ink,flex:1},taskRow:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:15,borderBottomWidth:1,borderColor:colors.line},check:{width:20,height:20,borderRadius:10,borderWidth:1,borderColor:colors.line}});
