import { useState } from 'react';
import { KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, Card, Chip, Label, ScreenHeader, SectionTitle } from '@/components/common/UI';
import { DogMascot } from '@/components/common/DogMascot';
import { EditableTaskList } from '@/components/planner/EditableTaskList';
import { colors } from '@/constants/theme';
import { usePlannerStore } from '@/store/usePlannerStore';
import { TaskStatus } from '@/types';

export default function Today(){
 const {tasks,checkIn,setCheckIn,updateTask,replan}=usePlannerStore();
 const [mode,setMode]=useState<'Cards'|'Timeline'>('Timeline');
 const [sheet,setSheet]=useState<'avoid'|'replan'|'progress'|null>(null);
 const [barrier,setBarrier]=useState('');
 const current=tasks.find(task=>task.status!=='done'&&task.type!=='routine')||tasks[0];
 const fixedTasks=tasks.filter(task=>task.locked||task.type==='fixed');
 return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">
  <ScreenHeader eyebrow="Sunday, 16 August" title="Today" right={<View style={s.weather}><Text>23°</Text><Ionicons name="partly-sunny-outline" size={19} color={colors.gold}/></View>}/>
  <Card style={s.check}><SectionTitle title="A gentle check-in" action={<Text style={s.saved}>Saved locally</Text>}/>
   <View style={s.inputRow}><View style={{flex:1}}><Label>Wake-up</Label><TextInput style={s.textInput} value={checkIn.wakeUp} onChangeText={wakeUp=>setCheckIn({wakeUp})}/></View><View style={{flex:1.7}}><Label>Fixed plans</Label><View style={s.fixedPlans}>{fixedTasks.length?fixedTasks.map(task=><View key={task.id} style={s.fixedPlan}><Ionicons name="pin" size={13} color={colors.coral}/><Text style={s.fixedTime}>{task.scheduledStart}</Text><Text numberOfLines={1} style={s.fixedTitle}>{task.title}</Text></View>):<Text style={s.fixedEmpty}>No fixed plans yet.</Text>}</View><Text style={s.fixedHint}>Tap a pin below to add more.</Text></View></View>
   <Label>Energy right now</Label><View style={s.chips}>{[1,2,3,4,5].map(number=><Chip key={number} label={String(number)} active={checkIn.energy===number} tint={colors.yellow} onPress={()=>setCheckIn({energy:number})}/>)}</View>
   <Label>Focused work feels realistic</Label><View style={s.chips}>{[2,4,6].map(hours=><Chip key={hours} label={`${hours}h`} active={checkIn.focusedHours===hours} tint={colors.sage} onPress={()=>setCheckIn({focusedHours:hours})}/>) }<Chip label="Custom"/></View>
   <Button onPress={()=>replan(checkIn.focusedHours)}>✨ Plan my day</Button>
  </Card>
  <View style={s.section}><SectionTitle title="Today's plan" action={<View style={s.toggle}>{(['Cards','Timeline'] as const).map(value=><Pressable key={value} onPress={()=>setMode(value)} style={[s.toggleItem,mode===value&&s.toggleOn]}><Text style={[s.toggleText,mode===value&&{color:colors.ink}]}>{value}</Text></Pressable>)}</View>}/><EditableTaskList tasks={tasks.slice(0,5)} mode={mode}/></View>
  <View style={s.nowLabel}><Label>Now · a kind next step</Label></View><Card style={s.now}><View style={s.nowTop}><DogMascot/><View style={{flex:1}}><Text style={s.nowTitle}>{current.title}</Text><Text style={s.next}>{current.nextAction||'Begin with the smallest useful step'}</Text><View style={s.metaRow}><Text style={s.pill}>◷ 45 min</Text><Text style={s.pill}>↗ {current.effort} effort</Text><Text style={[s.pill,{backgroundColor:colors.yellow}]}>+{current.coins} coins</Text></View></View></View><Button onPress={()=>setSheet('progress')}>Start</Button><View style={s.actionRow}><Button style={{flex:1}} kind="soft" onPress={()=>setSheet('avoid')}>I don’t want to</Button><Button style={{flex:1}} kind="ghost" onPress={()=>setSheet('replan')}>Replan</Button></View></Card>
  <Text style={s.reassure}>Reality changed? That’s information, not failure.</Text>
 </ScrollView><SupportSheet type={sheet} close={()=>setSheet(null)} barrier={barrier} setBarrier={setBarrier} onReplan={hours=>{replan(hours);setSheet(null)}} onStatus={status=>{updateTask(current.id,status);setSheet(null)}}/></SafeAreaView>;
}

function SupportSheet({type,close,barrier,setBarrier,onReplan,onStatus}:{type:string|null;close:()=>void;barrier:string;setBarrier:(value:string)=>void;onReplan:(hours:number)=>void;onStatus:(status:TaskStatus)=>void}){
 const options=['I don’t know how to start','I’m worried I won’t do it well','It feels too big','I’m too tired','It’s boring','I don’t have enough time'];
 return <Modal visible={!!type} transparent animationType="slide"><Pressable style={s.backdrop} onPress={close}/><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={s.sheet}>{type==='replan'?<><Label>Plans can bend</Label><Text style={s.sheetTitle}>What feels realistic today?</Text><Text style={s.sheetCopy}>Fixed plans stay in place. We’ll gently resize the rest.</Text><View style={s.replanRow}>{[2,3,4].map(hours=><Button key={hours} kind="soft" onPress={()=>onReplan(hours)}>{hours}h</Button>)}</View></>:type==='progress'?<><Label>Check in, not check up</Label><Text style={s.sheetTitle}>How did this step go?</Text><Text style={s.sheetCopy}>Planned 45 min. Any progress gives us useful information.</Text><Button onPress={()=>onStatus('done')}>Finished this step</Button><Button kind="soft" onPress={()=>onStatus('partial')}>Partially finished</Button><Button kind="ghost" onPress={()=>onStatus('todo')}>Didn’t really progress</Button></>:<><Label>Let’s make this lighter</Label><Text style={s.sheetTitle}>What’s getting in the way?</Text><View style={s.barriers}>{options.map(value=><Chip key={value} label={value} active={barrier===value} tint={colors.peach} onPress={()=>setBarrier(value)}/>)}</View><TextInput style={s.own} placeholder="Or tell me in your own words…"/><View style={s.suggestion}><Text style={s.suggestLabel}>A smaller next action</Text><Text style={s.suggestTitle}>{barrier==='I’m too tired'?'Open the document and read the last paragraph':'Create just 3 rough headings'}</Text><Text style={s.sheetCopy}>15 min · rough is enough</Text></View><Button onPress={close}>Do this instead</Button></>}</KeyboardAvoidingView></Modal>;
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},page:{padding:20,paddingBottom:120},weather:{flexDirection:'row',gap:7,alignItems:'center',backgroundColor:colors.yellow,paddingHorizontal:12,paddingVertical:8,borderRadius:99},check:{backgroundColor:'#FFFCF5'},saved:{fontSize:11,color:colors.green},inputRow:{flexDirection:'row',gap:12,marginBottom:16},textInput:{borderBottomWidth:1,borderColor:colors.line,paddingVertical:9,color:colors.ink,fontSize:14},fixedPlans:{gap:5,marginTop:7},fixedPlan:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:colors.peach,borderRadius:9,paddingHorizontal:8,paddingVertical:6},fixedTime:{fontSize:9,fontWeight:'800',color:colors.coral},fixedTitle:{fontSize:10,fontWeight:'700',color:colors.ink,flex:1},fixedEmpty:{fontSize:11,color:colors.muted,fontStyle:'italic',marginTop:7},fixedHint:{fontSize:9,color:colors.muted,marginTop:5},chips:{flexDirection:'row',gap:7,marginTop:8,marginBottom:16,flexWrap:'wrap'},section:{marginTop:28},toggle:{flexDirection:'row',padding:3,backgroundColor:colors.line,borderRadius:10},toggleItem:{paddingHorizontal:9,paddingVertical:5,borderRadius:8},toggleOn:{backgroundColor:colors.paper},toggleText:{fontSize:10,fontWeight:'700',color:colors.muted},nowLabel:{marginTop:16,marginBottom:8},now:{backgroundColor:'#FFFDF8'},nowTop:{flexDirection:'row',gap:12,alignItems:'center',marginBottom:15},nowTitle:{fontSize:23,fontWeight:'700',color:colors.ink},next:{fontSize:14,color:colors.muted,marginTop:4,lineHeight:20},metaRow:{flexDirection:'row',flexWrap:'wrap',gap:5,marginTop:10},pill:{fontSize:10,fontWeight:'600',paddingHorizontal:7,paddingVertical:5,backgroundColor:colors.blue,borderRadius:10,color:colors.ink},actionRow:{flexDirection:'row',gap:10,marginTop:10},reassure:{textAlign:'center',fontSize:12,color:colors.muted,marginTop:14},backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(50,48,44,.25)'},sheet:{position:'absolute',bottom:0,left:0,right:0,backgroundColor:colors.cream,borderTopLeftRadius:28,borderTopRightRadius:28,padding:24,paddingBottom:40,gap:10},sheetTitle:{fontSize:25,fontWeight:'700',color:colors.ink},sheetCopy:{color:colors.muted,fontSize:13,lineHeight:19},replanRow:{flexDirection:'row',gap:10,marginTop:12},barriers:{flexDirection:'row',flexWrap:'wrap',gap:7,marginVertical:8},own:{backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:12},suggestion:{padding:14,borderRadius:14,backgroundColor:colors.peach,marginVertical:5},suggestLabel:{fontSize:10,textTransform:'uppercase',letterSpacing:1,fontWeight:'700',color:colors.coral},suggestTitle:{fontSize:15,fontWeight:'700',color:colors.ink,marginVertical:4}});

